"""Daily-digest delivery — shared by the manual endpoint and the scheduler.

`send_digest_for_user` computes a user's personalized daily digest for **each**
birth profile they chose (a selected subset, or every saved profile) and delivers
one combined message on the channels they enabled in Settings → Notifications
(email via SMTP, browser push via Web Push). Each profile's section carries a
short "how the day looks" narrative — generated by the configured LLM when
available, and falling back to the rule-based highlights when it isn't — followed
by the day's key highlights. Both the "send me a test now" endpoint and the
background scheduler call this, so the delivery logic lives in exactly one place.
"""
import re
from typing import Any, Dict, List, Optional, Tuple

from astrology import AstrologyCompute, DEFAULT_AYANAMSA
from config import settings
from database import get_database
import digest_recipients
import email_service
import notifications
import timezones
import user_settings


async def resolve_profile(user_id: str, prefs: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """The single primary birth profile for a user: the one chosen in prefs
    (legacy `profile_id`), else their default, else their first saved profile,
    else None. Used for the scheduler's timezone lookup and as the last-resort
    fallback when no explicit set is configured."""
    db = get_database()
    profile = None
    if prefs.get("profile_id"):
        try:
            from bson import ObjectId
            profile = await db["saved_profiles"].find_one(
                {"_id": ObjectId(prefs["profile_id"]), "user_id": user_id})
        except Exception:
            profile = None
    if not profile:
        profile = await db["saved_profiles"].find_one(
            {"user_id": user_id, "is_default": True}
        ) or await db["saved_profiles"].find_one({"user_id": user_id})
    return profile


async def resolve_profiles(user_id: str, prefs: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Every birth profile the digest should cover, in a stable order.

    Precedence: `all_profiles` → every saved profile; else the explicit
    `profile_ids` set; else the legacy single-profile fallback
    (`resolve_profile`). Always returns real, owned profiles; an empty list means
    the user has nothing to send."""
    db = get_database()

    if prefs.get("all_profiles"):
        cursor = db["saved_profiles"].find({"user_id": user_id})
        profiles = [p async for p in cursor]
        if profiles:
            return profiles

    ids = prefs.get("profile_ids") or []
    if ids:
        from bson import ObjectId
        oids = []
        for i in ids:
            try:
                oids.append(ObjectId(str(i)))
            except Exception:
                continue
        if oids:
            cursor = db["saved_profiles"].find(
                {"_id": {"$in": oids}, "user_id": user_id})
            by_id = {str(p["_id"]): p async for p in cursor}
            # Preserve the user's chosen order, dropping any that no longer exist.
            profiles = [by_id[str(i)] for i in ids if str(i) in by_id]
            if profiles:
                return profiles

    single = await resolve_profile(user_id, prefs)
    return [single] if single else []


async def _digest_cfg(user_id: str):
    """LLM config for a scheduled/background narrative. There's no request here,
    so we rebuild it from the user's server-stored preferences (the same
    provider/model they picked in Settings, synced across devices), falling back
    to the server default, and top it up with their stored API key for keyed
    providers."""
    from llm_service import llm_service
    import user_settings

    prefs = {}
    try:
        prefs = await user_settings.get_preferences(user_id)
    except Exception:
        prefs = {}

    cfg = llm_service.resolve_config(
        provider_type=prefs.get("ai_provider_type") or None,
        model=prefs.get("ai_model") or None,
        base_url=prefs.get("ai_base_url") or None,
    )
    try:
        mt = int(prefs.get("ai_max_tokens") or 0)
        if mt:
            cfg.max_tokens = max(256, min(mt, 32768))
    except (TypeError, ValueError):
        pass
    try:
        if not cfg.api_key and cfg.provider_type.value in user_settings.KEYED_PROVIDERS:
            stored = await user_settings.get_api_key(user_id, cfg.provider_type.value)
            if stored:
                cfg.api_key = stored
    except Exception:
        pass
    return cfg


# Per-cadence wiring: which compute + which AI narrative + how to label the window.
# `basis` (solar/lunar) is only meaningful where both pravesha ladders have a rung —
# the fortnight is lunar-only (there is no solar fortnight), so it never takes one.
_CADENCES = {
    "daily": {
        "compute": "get_daily_digest", "analyze": "analyze_daily_digest",
        "noun": "digest", "route": "/daily-digest", "takes_basis": True,
        "takes_current": True,
    },
    "fortnightly": {
        "compute": "get_fortnightly_digest", "analyze": "analyze_fortnightly_digest",
        "noun": "fortnight", "route": "/fortnightly-digest", "takes_basis": False,
        "takes_current": False,
    },
    "monthly": {
        "compute": "get_monthly_digest", "analyze": "analyze_monthly_digest",
        "noun": "month", "route": "/monthly-digest", "takes_basis": True,
        "takes_current": False,
    },
}


def _offset_clock(offset: float) -> Dict[str, Any]:
    """A clock built from a fixed UTC offset (no zone → no DST)."""
    from datetime import datetime, timedelta, timezone as _tz
    local = datetime.now(_tz.utc) + timedelta(hours=offset or 0.0)
    return {
        "date": local.strftime("%Y-%m-%d"),
        "time": local.strftime("%H:%M"),
        "tz": offset or 0.0,
    }


async def observer_clock(user_id: str,
                         profiles: Optional[List[Dict[str, Any]]] = None
                         ) -> Optional[Dict[str, Any]]:
    """One clock for the whole digest — the reader's local date, time, and UTC
    offset right now — shared by every profile in the message.

    This is what makes a *scheduled* digest agree with the app's, and what keeps
    a multi-profile digest on a single day. The Daily Digest **page** already
    sends the browser's date and offset, so an in-app reading is about the
    reader's today. The scheduler has no browser: left to itself the engine
    derives "today" from the tz it was handed, which is each *birth profile's* —
    so a family read together can straddle two calendar days whenever their birth
    timezones differ. For someone born in India and living in the US that Indian
    date is also simply the wrong day every evening of their life.

    Precedence: the user's **current location** (zone-based, DST-correct) wins;
    failing that we fall back to the first profile's fixed birth offset so the
    whole digest still shares one day. Returns None only when there is no
    location and no profile to borrow an offset from."""
    loc = await user_settings.get_current_location(user_id)
    if loc:
        zone = loc.get("timezone")
        local = timezones.local_now(zone)
        if local is not None:
            return {
                "date": local.strftime("%Y-%m-%d"),
                "time": local.strftime("%H:%M"),
                "tz": timezones.offset_hours(zone, local),
            }

    # No current location: borrow the first profile's birth offset so every
    # profile in this digest is still read for the same calendar day.
    for p in (profiles or []):
        tz = (p.get("birth_details") or {}).get("timezone")
        if tz is not None:
            try:
                return _offset_clock(float(tz))
            except (TypeError, ValueError):
                continue
    return None


def _cadence(cadence: str) -> Dict[str, Any]:
    return _CADENCES.get(cadence, _CADENCES["daily"])


# An ingress line, e.g. "Jupiter enters Leo on 2026-10-31".
_INGRESS_RE = re.compile(r" enters .+ on \d{4}-\d{2}-\d{2}$")


def _split_highlights(highlights: List[str]) -> Tuple[List[str], List[str]]:
    """Partition a profile's highlight lines into (sky, personal).

    'Sky' facts depend only on the date and the reader's location, so they read
    identically for every profile on the same day: the panchanga headline, the
    current retrograde list, and upcoming sign-ingresses. Everything else (dasha,
    Sade-Sati, Jupiter-from-Moon, pravesha lagna, Tajaka yogas) is keyed to the
    individual chart. Splitting lets the combined digest print the shared sky once
    instead of repeating it under every name."""
    sky, personal = [], []
    for h in highlights:
        s = str(h)
        if (s.startswith("Retrograde now:")
                or " nakshatra" in s
                or _INGRESS_RE.search(s)):
            sky.append(s)
        else:
            personal.append(s)
    return sky, personal


def _shared_sky(blocks: List[Dict[str, Any]]) -> Optional[List[str]]:
    """The sky lines common to every block — returned only when there are 2+
    blocks that *all* carry the exact same sky set (i.e. they were computed for
    the same day and location). Otherwise None, and each section is rendered in
    full. This is what keeps a family digest from repeating the ingresses and
    retrogrades four times."""
    if len(blocks) < 2:
        return None
    sets = [tuple(b.get("sky") or []) for b in blocks]
    first = sets[0]
    if first and all(s == first for s in sets):
        return list(first)
    return None


async def _profile_block(user_id: str, profile: Dict[str, Any],
                         include_ai: bool, cadence: str = "daily",
                         basis: str = "solar",
                         observer: Optional[Dict[str, Any]] = None
                         ) -> Optional[Dict[str, Any]]:
    """Compute one profile's digest section for the given cadence (daily/
    fortnightly/monthly): name, window label, highlights, and an optional AI
    narrative. Returns None if the underlying calc failed.

    `observer` is the reader's current-location clock (see `observer_clock`); it
    fixes *which day* the digest is about. The birth details below stay untouched
    — they are the chart, and the chart does not move when the person does."""
    spec = _cadence(cadence)
    bd = profile.get("birth_details") or {}
    compute = getattr(AstrologyCompute, spec["compute"])
    kwargs = dict(
        dob=bd["dob"], tob=bd["tob"], place=bd.get("place", ""),
        lat=bd.get("latitude"), lon=bd.get("longitude"), tz=bd.get("timezone"),
        ayanamsa=DEFAULT_AYANAMSA)
    if spec["takes_basis"]:
        kwargs["basis"] = basis
    if observer:
        kwargs["date"] = observer["date"]
        if spec["takes_current"]:
            # Daily alone pins the transit moment to a wall clock; the fortnight
            # and month are windows, for which the date is the whole anchor.
            kwargs["current_time"] = observer["time"]
            kwargs["current_tz"] = observer["tz"]
    digest = compute(**kwargs)
    if digest.get("status") != "success":
        return None

    name = bd.get("name") or profile.get("profile_name") or "there"
    highlights = digest.get("highlights", [])
    # Daily carries a single `date`; weekly/monthly carry a start→end window.
    if cadence == "daily":
        window = digest.get("date")
    else:
        window = f"{digest.get('start_date')} → {digest.get('end_date')}"
    narrative = None
    if include_ai:
        try:
            from llm_service import llm_service
            cfg = await _digest_cfg(user_id)
            analyze = getattr(llm_service, spec["analyze"])
            text = await analyze(digest_data=digest, name=name, config=cfg)
            narrative = (text or "").strip() or None
        except Exception as e:  # LLM down/unconfigured/slow → fall back to highlights
            print(f"[digest] AI narrative skipped for {user_id}/{name}: {e}")
            narrative = None

    sky, personal = _split_highlights(highlights)
    return {
        "name": name,
        "date": window,
        "highlights": highlights,
        "sky": sky,
        "personal": personal,
        "narrative": narrative,
    }


def _render_text(blocks: List[Dict[str, Any]], date: str, noun: str) -> str:
    """Plain-text combined digest, one section per profile.

    When every section shares the same sky (2+ profiles on the same day), the
    common facts are printed once up top and each section keeps only what is
    personal to that chart."""
    parts = [f"Your {settings.SITE_NAME} Vedic {noun} for {date}", ""]
    multi = len(blocks) > 1
    shared = _shared_sky(blocks)
    if shared:
        parts.append("Across the sky today (the same for everyone):")
        parts.extend(f"• {h}" for h in shared)
        parts.append("")
    for b in blocks:
        if multi:
            parts.append(f"=== {b['name']} ===")
        else:
            parts.append(f"Hi {b['name']},")
        parts.append("")
        if b.get("narrative"):
            parts.append(b["narrative"])
            parts.append("")
        lines = b.get("personal") if shared else b.get("highlights")
        if lines:
            parts.append("For you:" if shared else "Highlights:")
            parts.extend(f"• {h}" for h in lines)
            parts.append("")
    parts.append(f"Open {settings.SITE_NAME} for the full reading.")
    return "\n".join(parts)


def _render_html(blocks: List[Dict[str, Any]], date: str, noun: str) -> str:
    """HTML combined digest, one section per profile (shared sky hoisted once)."""
    import html as _html

    def esc(s: str) -> str:
        return _html.escape(str(s))

    def narrative_html(text: str) -> str:
        # Render blank-line-separated paragraphs; keep it dependency-free.
        paras = [p.strip() for p in text.split("\n\n") if p.strip()]
        return "".join(f"<p>{esc(p)}</p>" for p in paras)

    multi = len(blocks) > 1
    shared = _shared_sky(blocks)
    out = [f"<p>Your {esc(settings.SITE_NAME)} Vedic {esc(noun)} for <b>{esc(date)}</b>:</p>"]
    if shared:
        out.append("<p style=\"margin:14px 0 4px;color:#8a6d3b\"><b>Across the sky today</b> "
                   "<span style=\"font-weight:normal\">(the same for everyone)</span></p>")
        out.append("<ul>" + "".join(f"<li>{esc(h)}</li>" for h in shared) + "</ul>")
    for b in blocks:
        out.append(f"<h3 style=\"margin:18px 0 6px\">{esc(b['name'])}</h3>"
                   if multi else f"<p>Hi {esc(b['name'])},</p>")
        if b.get("narrative"):
            out.append(narrative_html(b["narrative"]))
        lines = b.get("personal") if shared else b.get("highlights")
        if lines:
            out.append("<ul>" + "".join(f"<li>{esc(h)}</li>" for h in lines) + "</ul>")
    out.append(f"<p>Open {esc(settings.SITE_NAME)} for the full reading.</p>")
    return "".join(out)


async def send_digest_for_user(user_id: str, prefs: Optional[Dict[str, Any]] = None,
                               cadence: str = "daily") -> Dict[str, Any]:
    """Build + deliver a digest for one user at the given cadence (daily/
    fortnightly/monthly), covering every profile they chose in a single combined
    message. Returns `{status, sent:{email,push}, profiles:[names], date, cadence}`
    or `{status:"error",...}`. Never raises — the scheduler must survive one bad user."""
    db = get_database()
    if prefs is None:
        prefs = await notifications.get_prefs(user_id)
    spec = _cadence(cadence)
    basis = "lunar" if str(prefs.get("basis", "solar")).lower() == "lunar" else "solar"

    profiles = await resolve_profiles(user_id, prefs)
    if not profiles:
        return {"status": "error", "reason": "no_profile"}

    include_ai = prefs.get("include_ai", True)
    # One clock for the whole message: the reader's current location, or — failing
    # that — the first profile's birth offset, so every profile shares one day.
    observer = await observer_clock(user_id, profiles)
    blocks: List[Dict[str, Any]] = []
    for profile in profiles:
        try:
            block = await _profile_block(user_id, profile, include_ai, cadence,
                                         basis, observer)
        except Exception as e:  # one bad profile shouldn't sink the whole digest
            print(f"[digest] profile calc failed for {user_id}: {e}")
            block = None
        if block:
            # Where this subject's own copy goes (empty → the owner's combined copy).
            block["_email"] = (profile.get("notify_email") or "").strip().lower() or None
            blocks.append(block)

    if not blocks:
        return {"status": "error", "reason": "calc_failed"}

    date = blocks[0]["date"]
    noun = spec["noun"]
    names = [b["name"] for b in blocks]
    subject = f"Your {settings.SITE_NAME} {noun} — {date}"
    text = _render_text(blocks, date, noun)
    html = _render_html(blocks, date, noun)

    sent = {"email": False, "push": 0, "recipients": 0}
    if prefs.get("email"):
        user = await db["users"].find_one({"username": user_id})
        owner_email = (user or {}).get("email")
        owner_norm = (owner_email or "").strip().lower()

        # Each subject with their own address gets a personal copy carrying only
        # their section(s); everyone without one stays in the owner's combined copy.
        groups: Dict[str, List[Dict[str, Any]]] = {}
        for b in blocks:
            addr = b.get("_email")
            if not addr or addr == owner_norm:
                continue  # owner reads this one in the combined copy
            groups.setdefault(addr, []).append(b)

        owner_name = (user or {}).get("username") or user_id
        base = settings.APP_BASE_URL.rstrip("/")
        for addr, gblocks in groups.items():
            # Double opt-in: only deliver to a subject who has confirmed. Pending,
            # unsubscribed or never-invited addresses are skipped — they still
            # appear in the owner's combined copy above.
            rec = await digest_recipients.get(user_id, addr)
            if not rec or rec.get("status") != digest_recipients.CONFIRMED:
                continue
            unsub_url = f"{base}/digest/unsubscribe?token={rec['token']}"
            g_date = gblocks[0]["date"]
            g_subject = f"Your {settings.SITE_NAME} {noun} — {g_date}"
            g_text = (_render_text(gblocks, g_date, noun)
                      + email_service.digest_footer_text(owner_name, unsub_url))
            g_html = (_render_html(gblocks, g_date, noun)
                      + email_service.digest_footer_html(owner_name, unsub_url))
            try:
                if await email_service.send_daily_digest(addr, g_subject, g_text, g_html):
                    sent["recipients"] += 1
            except Exception as e:
                print(f"[digest] recipient send failed for {addr}: {e}")

        # The owner's combined copy always covers every profile (full overview).
        if owner_email:
            sent["email"] = await email_service.send_daily_digest(
                owner_email, subject, text, html)
            if sent["email"]:
                sent["recipients"] += 1
    if prefs.get("push"):
        if len(blocks) > 1:
            body = f"Your {noun} for {', '.join(names)} is ready."
        else:
            hl = blocks[0]["highlights"]
            body = hl[0] if hl else f"Your Vedic {noun} is ready."
        sent["push"] = await notifications.send_push(user_id, {
            "title": subject,
            "body": body,
            "url": spec["route"],
        })

    return {"status": "ok", "sent": sent, "profiles": names, "date": date, "cadence": cadence}
