"""Daily-digest delivery — shared by the manual endpoint and the scheduler.

`send_digest_for_user` computes a user's personalized daily digest for **each**
birth profile they chose (a selected subset, or every saved profile) and delivers
one combined message on the channels they enabled in Settings → Notifications
(email via SMTP, browser push via Web Push). Each profile's section carries a
short "how the day looks" narrative — generated by the configured LLM when
available, and falling back to the rule-based highlights when it isn't — followed
by the day's key highlights. Both the "send me a test now" endpoint and the
background scheduler call this, so the delivery logic lives in exactly one place.
"""
from typing import Any, Dict, List, Optional

from astrology import AstrologyCompute, DEFAULT_AYANAMSA
from config import settings
from database import get_database
import email_service
import notifications


async def resolve_profile(user_id: str, prefs: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """The single primary birth profile for a user: the one chosen in prefs
    (legacy `profile_id`), else their default, else their first saved profile,
    else None. Used for the scheduler's timezone lookup and as the last-resort
    fallback when no explicit set is configured."""
    db = get_database()
    profile = None
    if prefs.get("profile_id"):
        try:
            from bson import ObjectId
            profile = await db["saved_profiles"].find_one(
                {"_id": ObjectId(prefs["profile_id"]), "user_id": user_id})
        except Exception:
            profile = None
    if not profile:
        profile = await db["saved_profiles"].find_one(
            {"user_id": user_id, "is_default": True}
        ) or await db["saved_profiles"].find_one({"user_id": user_id})
    return profile


async def resolve_profiles(user_id: str, prefs: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Every birth profile the digest should cover, in a stable order.

    Precedence: `all_profiles` → every saved profile; else the explicit
    `profile_ids` set; else the legacy single-profile fallback
    (`resolve_profile`). Always returns real, owned profiles; an empty list means
    the user has nothing to send."""
    db = get_database()

    if prefs.get("all_profiles"):
        cursor = db["saved_profiles"].find({"user_id": user_id})
        profiles = [p async for p in cursor]
        if profiles:
            return profiles

    ids = prefs.get("profile_ids") or []
    if ids:
        from bson import ObjectId
        oids = []
        for i in ids:
            try:
                oids.append(ObjectId(str(i)))
            except Exception:
                continue
        if oids:
            cursor = db["saved_profiles"].find(
                {"_id": {"$in": oids}, "user_id": user_id})
            by_id = {str(p["_id"]): p async for p in cursor}
            # Preserve the user's chosen order, dropping any that no longer exist.
            profiles = [by_id[str(i)] for i in ids if str(i) in by_id]
            if profiles:
                return profiles

    single = await resolve_profile(user_id, prefs)
    return [single] if single else []


async def _digest_cfg(user_id: str):
    """LLM config for a scheduled/background narrative: the server default
    provider, topped up with the user's stored API key for keyed providers.
    There's no request here, so we can't use the per-request resolver."""
    from llm_service import llm_service
    cfg = llm_service.resolve_config()
    try:
        import user_settings
        if not cfg.api_key and cfg.provider_type.value in user_settings.KEYED_PROVIDERS:
            stored = await user_settings.get_api_key(user_id, cfg.provider_type.value)
            if stored:
                cfg.api_key = stored
    except Exception:
        pass
    return cfg


async def _profile_block(user_id: str, profile: Dict[str, Any],
                         include_ai: bool) -> Optional[Dict[str, Any]]:
    """Compute one profile's digest section: name, date, highlights, and an
    optional AI narrative. Returns None if the underlying calc failed."""
    bd = profile.get("birth_details") or {}
    digest = AstrologyCompute.get_daily_digest(
        dob=bd["dob"], tob=bd["tob"], place=bd.get("place", ""),
        lat=bd.get("latitude"), lon=bd.get("longitude"), tz=bd.get("timezone"),
        ayanamsa=DEFAULT_AYANAMSA)
    if digest.get("status") != "success":
        return None

    name = bd.get("name") or profile.get("profile_name") or "there"
    highlights = digest.get("highlights", [])
    narrative = None
    if include_ai:
        try:
            from llm_service import llm_service
            cfg = await _digest_cfg(user_id)
            text = await llm_service.analyze_daily_digest(
                digest_data=digest, name=name, config=cfg)
            narrative = (text or "").strip() or None
        except Exception as e:  # LLM down/unconfigured/slow → fall back to highlights
            print(f"[digest] AI narrative skipped for {user_id}/{name}: {e}")
            narrative = None

    return {
        "name": name,
        "date": digest.get("date"),
        "highlights": highlights,
        "narrative": narrative,
    }


def _render_text(blocks: List[Dict[str, Any]], date: str) -> str:
    """Plain-text combined digest, one section per profile."""
    parts = [f"Your {settings.SITE_NAME} Vedic digest for {date}", ""]
    multi = len(blocks) > 1
    for b in blocks:
        if multi:
            parts.append(f"=== {b['name']} ===")
        else:
            parts.append(f"Hi {b['name']},")
        parts.append("")
        if b.get("narrative"):
            parts.append(b["narrative"])
            parts.append("")
        if b.get("highlights"):
            parts.append("Today's highlights:")
            parts.extend(f"• {h}" for h in b["highlights"])
            parts.append("")
    parts.append(f"Open {settings.SITE_NAME} for the full reading.")
    return "\n".join(parts)


def _render_html(blocks: List[Dict[str, Any]], date: str) -> str:
    """HTML combined digest, one section per profile."""
    import html as _html

    def esc(s: str) -> str:
        return _html.escape(str(s))

    def narrative_html(text: str) -> str:
        # Render blank-line-separated paragraphs; keep it dependency-free.
        paras = [p.strip() for p in text.split("\n\n") if p.strip()]
        return "".join(f"<p>{esc(p)}</p>" for p in paras)

    multi = len(blocks) > 1
    out = [f"<p>Your {esc(settings.SITE_NAME)} Vedic digest for <b>{esc(date)}</b>:</p>"]
    for b in blocks:
        out.append(f"<h3 style=\"margin:18px 0 6px\">{esc(b['name'])}</h3>"
                   if multi else f"<p>Hi {esc(b['name'])},</p>")
        if b.get("narrative"):
            out.append(narrative_html(b["narrative"]))
        if b.get("highlights"):
            out.append("<ul>" + "".join(f"<li>{esc(h)}</li>" for h in b["highlights"]) + "</ul>")
    out.append(f"<p>Open {esc(settings.SITE_NAME)} for the full reading.</p>")
    return "".join(out)


async def send_digest_for_user(user_id: str, prefs: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Build + deliver the daily digest for one user, covering every profile they
    chose in a single combined message. Returns
    `{status, sent:{email,push}, profiles:[names], date}` or `{status:"error",...}`.
    Never raises — the scheduler must survive one bad user."""
    db = get_database()
    if prefs is None:
        prefs = await notifications.get_prefs(user_id)

    profiles = await resolve_profiles(user_id, prefs)
    if not profiles:
        return {"status": "error", "reason": "no_profile"}

    include_ai = prefs.get("include_ai", True)
    blocks: List[Dict[str, Any]] = []
    for profile in profiles:
        try:
            block = await _profile_block(user_id, profile, include_ai)
        except Exception as e:  # one bad profile shouldn't sink the whole digest
            print(f"[digest] profile calc failed for {user_id}: {e}")
            block = None
        if block:
            blocks.append(block)

    if not blocks:
        return {"status": "error", "reason": "calc_failed"}

    date = blocks[0]["date"]
    names = [b["name"] for b in blocks]
    subject = f"Your {settings.SITE_NAME} digest — {date}"
    text = _render_text(blocks, date)
    html = _render_html(blocks, date)

    sent = {"email": False, "push": 0}
    if prefs.get("email"):
        user = await db["users"].find_one({"username": user_id})
        if user and user.get("email"):
            sent["email"] = await email_service.send_daily_digest(user["email"], subject, text, html)
    if prefs.get("push"):
        if len(blocks) > 1:
            body = f"Digests for {', '.join(names)} are ready."
        else:
            hl = blocks[0]["highlights"]
            body = hl[0] if hl else "Your daily Vedic digest is ready."
        sent["push"] = await notifications.send_push(user_id, {
            "title": subject,
            "body": body,
            "url": "/daily-digest",
        })

    return {"status": "ok", "sent": sent, "profiles": names, "date": date}
