"""Server-side Life Report generation (§45).

The Life Report is seven long-form AI chapters. It used to be generated by a loop
in the browser: the page requested chapter 1, waited, requested chapter 2, and so
on. On an iPhone that breaks as soon as the screen locks — iOS suspends the page's
JavaScript and kills the in-flight request, so generation stopped part-way. Worse,
the assembled report was only persisted once *every* chapter had finished, so a
phone going to sleep mid-run threw away everything generated so far.

Generation now runs on the server as a background job. The client starts a job and
then only polls it, so nothing depends on the phone staying awake: each chapter is
written to the job document the moment it lands, and the run continues even if the
screen locks, the tab closes, or the user navigates away.

When the last chapter completes, the assembled markdown is saved to the unified AI
history as an ordinary reading. Saves are additive — a regenerate leaves previous
reports in history rather than overwriting them — so the page can re-open the most
recent report on return and older ones stay browsable.
"""
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from bson import ObjectId

import conversations as convo
from chart_context import build_chart_context
from database import get_database
from llm_service import llm_service

COLLECTION = "life_report_jobs"

# A running job writes its heartbeat (`updated_at`) after every chapter. If the
# process dies mid-run (pod restart, redeploy) the document is left claiming to be
# running forever, which would wedge the UI on a spinner and block a restart. Any
# running job that hasn't touched its heartbeat in this long is treated as failed.
# Generous, because a single chapter on a slow local Ollama can legitimately take
# several minutes.
STALE_AFTER_SEC = 15 * 60

STATUS_RUNNING = "running"
STATUS_DONE = "done"
STATUS_ERROR = "error"
STATUS_CANCELLED = "cancelled"


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _as_utc(value: Any) -> Optional[datetime]:
    """Mongo hands back naive datetimes; compare them as UTC."""
    if not isinstance(value, datetime):
        return None
    return value if value.tzinfo else value.replace(tzinfo=timezone.utc)


def _is_stale(doc: Dict[str, Any]) -> bool:
    if doc.get("status") != STATUS_RUNNING:
        return False
    beat = _as_utc(doc.get("updated_at")) or _as_utc(doc.get("created_at"))
    if not beat:
        return True
    return (_now() - beat).total_seconds() > STALE_AFTER_SEC


def assemble_markdown(chapters: List[Dict[str, Any]]) -> str:
    """The finished report: every completed chapter under its own heading."""
    parts = []
    for ch in chapters:
        if ch.get("status") == "done" and ch.get("text"):
            parts.append(f"## {ch.get('title') or ch.get('key')}\n\n{ch['text'].strip()}")
    return "\n\n".join(parts)


def _serialize(doc: Dict[str, Any]) -> Dict[str, Any]:
    chapters = doc.get("chapters") or []
    done = sum(1 for c in chapters if c.get("status") == STATUS_DONE)
    return {
        "job_id": str(doc["_id"]),
        "status": doc.get("status"),
        "profile_id": doc.get("profile_id"),
        "person_name": doc.get("person_name"),
        "chapters": [
            {
                "key": c.get("key"),
                "title": c.get("title"),
                "status": c.get("status", "pending"),
                "text": c.get("text", ""),
            }
            for c in chapters
        ],
        "done_count": done,
        "total": len(chapters),
        "provider": doc.get("provider"),
        "model": doc.get("model"),
        "error": doc.get("error"),
        "reading_id": doc.get("reading_id"),
        "markdown": assemble_markdown(chapters),
        "created_at": (_as_utc(doc.get("created_at")) or _now()).isoformat(),
        "updated_at": (_as_utc(doc.get("updated_at")) or _now()).isoformat(),
    }


async def _reap_if_stale(doc: Dict[str, Any]) -> Dict[str, Any]:
    """Flip an abandoned running job to error so the UI can offer a restart."""
    if not _is_stale(doc):
        return doc
    db = get_database()
    await db[COLLECTION].update_one(
        {"_id": doc["_id"], "status": STATUS_RUNNING},
        {"$set": {"status": STATUS_ERROR,
                  "error": "Generation was interrupted on the server. Start it again to continue.",
                  "updated_at": _now()}},
    )
    doc = {**doc, "status": STATUS_ERROR,
           "error": "Generation was interrupted on the server. Start it again to continue."}
    return doc


async def get_latest(user_id: str, profile_id: Optional[str]) -> Optional[Dict[str, Any]]:
    """The newest job for this user+profile, with stale runs already reaped."""
    db = get_database()
    query: Dict[str, Any] = {"user_id": user_id}
    if profile_id:
        query["profile_id"] = profile_id
    doc = await db[COLLECTION].find_one(query, sort=[("created_at", -1)])
    if not doc:
        return None
    doc = await _reap_if_stale(doc)
    return _serialize(doc)


async def get_running(user_id: str, profile_id: Optional[str]) -> Optional[Dict[str, Any]]:
    """A live job for this user+profile, if one is genuinely still running."""
    db = get_database()
    query: Dict[str, Any] = {"user_id": user_id, "status": STATUS_RUNNING}
    if profile_id:
        query["profile_id"] = profile_id
    doc = await db[COLLECTION].find_one(query, sort=[("created_at", -1)])
    if not doc:
        return None
    doc = await _reap_if_stale(doc)
    if doc.get("status") != STATUS_RUNNING:
        return None
    return _serialize(doc)


async def create_job(user_id: str, *, profile_id: Optional[str],
                     person_name: Optional[str], birth_details: Dict[str, Any],
                     ayanamsa: Optional[str], sections: Optional[dict] = None,
                     vargas: Optional[list] = None) -> Dict[str, Any]:
    """Register a new run with every chapter pending."""
    db = get_database()
    now = _now()
    doc = {
        "user_id": user_id,
        "profile_id": profile_id,
        "person_name": person_name,
        "birth_details": birth_details,
        "ayanamsa": ayanamsa,
        "sections": sections,
        "vargas": vargas,
        "status": STATUS_RUNNING,
        "chapters": [
            {"key": key, "title": title, "status": "pending", "text": ""}
            for (key, title, _focus) in llm_service.LIFE_REPORT_CHAPTERS
        ],
        "provider": None,
        "model": None,
        "error": None,
        "reading_id": None,
        "created_at": now,
        "updated_at": now,
    }
    res = await db[COLLECTION].insert_one(doc)
    doc["_id"] = res.inserted_id
    return _serialize(doc)


async def cancel_job(user_id: str, job_id: str) -> bool:
    """Ask a running job to stop; the loop notices before its next chapter."""
    if not ObjectId.is_valid(job_id):
        return False
    db = get_database()
    res = await db[COLLECTION].update_one(
        {"_id": ObjectId(job_id), "user_id": user_id, "status": STATUS_RUNNING},
        {"$set": {"status": STATUS_CANCELLED, "updated_at": _now()}},
    )
    return res.modified_count > 0


async def _set_chapter(job_id: ObjectId, index: int, status: str, text: str = "") -> None:
    db = get_database()
    await db[COLLECTION].update_one(
        {"_id": job_id},
        {"$set": {f"chapters.{index}.status": status,
                  f"chapters.{index}.text": text,
                  "updated_at": _now()}},
    )


async def _still_running(job_id: ObjectId) -> bool:
    """False once the user cancels, so the loop can bail between chapters."""
    db = get_database()
    doc = await db[COLLECTION].find_one({"_id": job_id}, {"status": 1})
    return bool(doc) and doc.get("status") == STATUS_RUNNING


async def run_job(job_id: str, user_id: str, cfg) -> None:
    """Generate every chapter in order, persisting each as it lands.

    Runs detached from the request that started it, so it keeps going while the
    client is asleep or gone. Never raises: a failure is recorded on the job
    document, which is what the polling client reads.
    """
    db = get_database()
    oid = ObjectId(job_id)
    doc = await db[COLLECTION].find_one({"_id": oid})
    if not doc:
        return

    birth_details = doc.get("birth_details") or {}
    person = doc.get("person_name") or birth_details.get("name") or "this person"
    chapters = doc.get("chapters") or []

    try:
        chart_data = build_chart_context(
            birth_details=birth_details,
            ayanamsa=doc.get("ayanamsa"),
            sections=doc.get("sections"),
            vargas=doc.get("vargas"),
        )
    except Exception as e:  # chart context is required for every chapter
        await db[COLLECTION].update_one(
            {"_id": oid},
            {"$set": {"status": STATUS_ERROR, "error": f"Could not build the chart: {e}",
                      "updated_at": _now()}},
        )
        return

    # Chapter prompts keyed by the engine's canonical list, so a job created by an
    # older build still resolves its titles/focus correctly.
    focus_by_key = {k: (title, focus) for (k, title, focus) in llm_service.LIFE_REPORT_CHAPTERS}

    for index, ch in enumerate(chapters):
        if not await _still_running(oid):
            return  # cancelled between chapters
        if ch.get("status") == STATUS_DONE and ch.get("text"):
            continue  # already generated (resumed run)

        key = ch.get("key")
        title, focus = focus_by_key.get(key, (ch.get("title") or key, ""))
        await _set_chapter(oid, index, "active")
        try:
            text = await llm_service.generate_life_report_chapter(
                chart_data=chart_data, title=title, focus=focus,
                name=person, config=cfg)
        except Exception as e:
            await _set_chapter(oid, index, STATUS_ERROR)
            await db[COLLECTION].update_one(
                {"_id": oid},
                {"$set": {"status": STATUS_ERROR, "error": str(e), "updated_at": _now()}},
            )
            return
        await _set_chapter(oid, index, STATUS_DONE, text or "")

    if not await _still_running(oid):
        return

    # Every chapter landed — assemble once and file it in the unified history.
    doc = await db[COLLECTION].find_one({"_id": oid})
    markdown = assemble_markdown((doc or {}).get("chapters") or [])
    reading_id = None
    try:
        reading_id = await convo.save_reading(
            user_id, source="life_report",
            title=f"Life Report — {person}",
            text=markdown,
            context={"person_name": doc.get("person_name"), "ayanamsa": doc.get("ayanamsa")},
            profile_id=doc.get("profile_id"),
            birth_details=birth_details,
            model=getattr(cfg, "model", None),
            provider=getattr(getattr(cfg, "provider_type", None), "value", None),
        )
    except Exception as e:  # history is a nice-to-have; the job itself still succeeded
        print(f"Failed to persist life report to history: {e}")

    await db[COLLECTION].update_one(
        {"_id": oid},
        {"$set": {"status": STATUS_DONE,
                  "reading_id": reading_id,
                  "provider": getattr(getattr(cfg, "provider_type", None), "value", None),
                  "model": getattr(cfg, "model", None),
                  "updated_at": _now()}},
    )
